version: '3'
services:
    mock_server:
        image: server
        container_name: mock_server
        build: ./server
        ports:
          - 80:8899

    test_client:
        image: client
        container_name: test_client
        build: ./client
        environment:
          - HTTP_PROXY=mock_server:8899
          - HTTPS_PROXY=mock_server:8899
