version: '3'
services:
    mock_server:
        image: server
        container_name: mock_server
        build: ./server
        ports:
          - 80:8899
        networks:
            my_net:
                ipv4_address: 172.26.0.3

    test_client:
        image: client
        container_name: test_client
        build: ./client
        environment:
          - HTTP_PROXY=proxy:8899
          - HTTPS_PROXY=proxy:8899
        extra_hosts:
         - "proxy:172.26.0.3"
        networks:
            my_net:
                ipv4_address: 172.26.0.4
networks:
    my_net:
        ipam:
            driver: default
            config:
                - subnet: 172.26.0.0/16
